# Server configuration
server.port=8080
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

# Hibernate configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# Database connection (AWS RDS)
spring.datasource.url=jdbc:mysql://yoga-data-1.ctsus488umfx.ap-south-1.rds.amazonaws.com:3306/yogamysqldata
spring.datasource.username=admin
spring.datasource.password=bhw6ssnstjhfmT1O3gXV
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Entity scan (optional if annotated correctly)
spring.jpa.packages-to-scan=com
